name: Build

on: push

jobs:
  publish:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          linux,
          windows,
          macos
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/timetable
            asset_name: timetable-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/timetable.exe
            asset_name: timetable-win
          - name: macos
            os: macos-latest
            artifact_name: target/release/timetable
            asset_name: timetable-mac

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --release --locked

    - name: Upload binaries to release
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}